version: "3"

services:
  mariadb:
    container_name: "whuk_mariadb"
    image: wodby/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: whukRootPass
      MYSQL_DATABASE: whuk
      MYSQL_USER: whukUser
      MYSQL_PASSWORD: whukPass
  php:
    container_name: "whuk_php"
    image: wodby/php:latest
    depends_on:
      - mariadb
      - redis
    environment:
      PHP_FPM_CLEAR_ENV: "no"
      MYSQL_DATABASE: whuk
      MYSQL_HOSTNAME: mariadb
      MYSQL_USER: whukUser
      MYSQL_PASSWORD: whukPass
      REDIS_HOST: redis
    volumes:
      - ./:/var/www/html:cached
  nginx:
    container_name: "whuk_nginx"
    image: wodby/nginx:latest
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/public_html/
      NGINX_VHOST_PRESET: php
    volumes:
      - ./:/var/www/html:cached
  redis:
    container_name: "whuk_redis"
    image: wodby/redis:latest
  mailhog:
    container_name: "whuk_mailhog"
    image: mailhog/mailhog:latest
